#!/bin/bash
# This script expects the standdard JMeter command parameters.
#

# Install jmeter plugins available on /plugins volume
if [ -d $JMETER_CUSTOM_PLUGINS_FOLDER ]
then
    for plugin in ${JMETER_CUSTOM_PLUGINS_FOLDER}/*.jar; do
        cp $plugin ${JMETER_HOME}/lib/ext
    done;
fi

# Execute JMeter command
set -e
freeMem=`awk '/MemAvailable/ { print int($2/1024) }' /proc/meminfo`

[[ -z ${JVM_XMN} ]] && JVM_XMN=$(($freeMem/10*2))
[[ -z ${JVM_XMS} ]] && JVM_XMS=$(($freeMem/10*8))
[[ -z ${JVM_XMX} ]] && JVM_XMX=$(($freeMem/10*8))

export JVM_ARGS="-Xmn${JVM_XMN}m -Xms${JVM_XMS}m -Xmx${JVM_XMX}m -Dserver.rmi.ssl.disable=true"

echo "START Running Jmeter on `date`"
echo "JVM_ARGS=${JVM_ARGS}"
echo "jmeter args=$@"

# Keep entrypoint simple: we must pass the standard JMeter arguments
EXTRA_ARGS=-Dlog4j2.formatMsgNoLookups=true
echo "jmeter ALL ARGS=${EXTRA_ARGS} $@"


echo prepare infrastrcuture  create tests autogenerated result folder
now=$(date +%Y%m%d_%H%M%S)
resultFolderName=${JMETER_RESULTS}/load_test_$now
mkdir -p $resultFolderName
echo $resultFolderName has been created

# Setup report folder
reportFolderName=$resultFolderName/report
reportTmpFolderName=$resultFolderName/report_tmp
mkdir -p $reportFolderName
echo $reportFolderName has created
mkdir -p $reportTmpFolderName
echo $reportTmpFolderName has created

# Setup JMeter script and properites file to be used in the test
jmeterScriptpath=${JMETER_SCRIPTS}/${JMETER_TEST_SCRIPT_NAME}
jmeterResultFilePath=$resultFolderName/results.jtl
jmeterLogFilePath=$resultFolderName/logs.txt
jmeterCustomPropFilePath=${JMETER_SCRIPTS}/${JMETER_TEST_SETTINGS_NAME}

echo script path is $jmeterScriptpath
echo prop path is $jmeterCustomPropFilePath
# Print Varibles 
echo jmeterResultFilePath is $jmeterResultFilePath
echo jmeterLogFilePath is $jmeterLogFilePath

# Start Test
echo start Jmeter script
jmeter ${EXTRA_ARGS} $@ -n -t $jmeterScriptpath -l $jmeterResultFilePath -j $jmeterLogFilePath -p $jmeterCustomPropFilePath -Jjmeter.reportgenerator.temp_dir=$reportTmpFolderName -JCookieManager.save.cookies=true -e -o $reportFolderName
echo "END Running Jmeter on `date`"